### ISSUE TITLE
Wiki Integration

### ISSUE THREAD

**Issue by cdrelich** [zenirc/zenircbot#19]
Add integration between Wikis and the bot.  MediaWiki is the desired target, but this should be done in a that other Wikis can be added in later.  A few options should be available, such as notify at the creation of page, notify on the modification of page (when not marked as a minor edit), notify on any page modifications (probably super spammy, also be careful of also tracking modification of user contribution pages with this or it might double up on notifications).  This should be simple via handling an RSS feed.

**Comment by wraithan** [comment]
I'd prefer to do this via callbacks I'll look to see if MediaWiki can call a webhook url when these actions happen. Barring that I'll implement it using an RSS feed reader.
