### ISSUE TITLE
The bot should be more robust about directed messages vs commands vs pm vs channel chatter

### ISSUE THREAD

**Issue by wraithan** [zenirc/zenircbot#40]
Maybe the bot should prepare things or perhaps a service should like how @donpdonp wrote his IRC bot.

**Comment by donpdonp** [comment]
thats just what I was thinking :). the 'semantic' service listens for messages and analyses them to see if they are directed at the bot, then rebroadcasts an annotated version of the message to say yes/no the message is a direct one.

https://github.com/donpdonp/neuronirc/blob/master/lib/neuron/dendrites/semantic.rb

**Comment by wraithan** [comment]
Yeah, I like it but at the same time I am a bit weary of making all the services rely on something like that. I can see something like that being part of the default list of auto start scripts. Then it wont be as big of a deal assuming people use admin.js.

**Comment by wraithan** [comment]
Going to write it as a service with a new message type, directed message:

``` json
"data": {
    "sender": "Wraithan",
    "raw_message": "!commands",
    "message": "commands",
    "channel": "#pdxbots"
}
```

Catch a preset prefix, nick: , and private messages. In the case of a private message the channel will be set to the name of the sender.
