### ISSUE TITLE
monitor Bailey's Taproom (Portland, OR)

### ISSUE THREAD

**Issue by donpdonp** [zenirc/zenircbot#50]
monitor the API at baileystaproom.com (cant find docs on it yet) and announce when new beers come on tap.

in response to
https://twitter.com/#!/zacduncan/status/175751339387781121

**Comment by wraithan** [comment]
Pinged zacduncan in order to see if BA provides an API that I was unable to find.

Also, lets expand on this idea, Bailey's is cool and all, but what about hitting up taplister or individual sites to get the list at Apex, Side Door, and our other favorite drinking holes.

**Comment by donpdonp** [comment]
this json feed just became available

http://ec2-50-112-236-55.us-west-2.compute.amazonaws.com/api/baileys

**Comment by wraithan** [comment]
I appreciate the update on this @donpdonp ! I'll keep this in mind when I go through to implement this.
