### ISSUE TITLE
heartbeat the connection so we can see if we got DCd

### ISSUE THREAD

**Issue by wraithan** [zenirc/zenircbot#79]
Most clients do this, the server does this to the client, lets take after all of them and reconnect if we don't get a pong for a while after a ping.

Ping every 30s, miss 4 and you reconnect. Seems reasonable.

**Comment by aaronpk** [comment]
Good idea! Probably should allow overrides of the values in the config file, but that seems like a sane default.

**Comment by wraithan** [comment]
Of course, considering some servers don't support ping (I know, wtf?)

Putting in 3.0 as it changes some default behavior in ways that may break some servers.

**Comment by almet** [comment]
+1 on this :)

**Comment by aaronpk** [comment]
> it changes some default behavior in ways that may break some servers.

What is this in reference to specifically? I have this working pretty well on my fork now, doesn't seem to have caused any adverse side effects at least in my initial testing.

**Comment by wraithan** [comment]
It changes the default settings to add a new one and the shitty programmer who wrote zenircbot didn't make it so you could only define a subset of permissions.

**Comment by aaronpk** [comment]
Couldn't the code just check for the presence of the config setting, and if it's not there then ping checks aren't enabled?

**Comment by wraithan** [comment]
True, I guess I could just fix the config loader in the same release as I add heartbeat.

**Comment by aaronpk** [comment]
Ok well I'll have a PR for adding ping checks in a bit anyway. Opinions on the config parameter names for the interval and the number of pings missed before a reconnect?

**Comment by wraithan** [comment]
3.0-devel has this. Closing.
