### ISSUE TITLE
Broadcast a "connected" message to give services a chance to send "join" messages

### ISSUE THREAD

**Issue by aaronpk** [zenirc/zenircbot#81]
When the bot finishes connecting to the server and joining any channels in its config file, it would be cool if it sent a message that services could subscribe to. The services could then do whatever they need, such as telling the bot to join more channels.

I have a service where the channels the bot should join are defined in a cloud service completely separate from the bot. Currently I have a cron task set up in the service that makes the API call and sends a "join" command for all the channels defined. This leaves me in the state where if the bot re-connects, it won't be in those channels until the cron job runs. I was thinking a more event-driven approach would solve it. This seems easier than coming up with a way for the services to edit the bot's config file to add new channels.

**Comment by wraithan** [comment]
I like it.
